on: [push, pull_request]
name: Release
env:
  BASE_REPO: paddleflow
  PF_SERVER: paddleflow-server
  PF_CSI: pfs-csi-plugin
jobs:
  compile:
    strategy:
      matrix:
        go-version: [1.18.x]
        goos: [linux]
        goarch: [amd64]
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run build
        run: make all
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
      - name: Packaging
        run: tar -zcvf paddleflow-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz output/
      - name: Uploading assets
        uses: actions/upload-artifact@v3
        with:
          name: paddleflow-${{ matrix.goos }}-${{ matrix.goarch }}
          path: paddleflow-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
  publish:
    strategy:
      matrix:
        go-version: [ 1.18.x ]
        goos: [ linux ]
        goarch: [ amd64 ]
    runs-on: ubuntu-latest
    steps:
      - name: CreateRelease
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: |
            Release.txt
            paddleflow-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
            LICENSE

